package org.hanqim.mcpdict;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER".
 */
public class User {

    private Long id;
    /** Not-null value. */
    private String unicode;
    private String comment;
    /** Not-null value. */
    private java.util.Date localtime;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String unicode, String comment, java.util.Date localtime) {
        this.id = id;
        this.unicode = unicode;
        this.comment = comment;
        this.localtime = localtime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUnicode() {
        return unicode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUnicode(String unicode) {
        this.unicode = unicode;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    /** Not-null value. */
    public java.util.Date getLocaltime() {
        return localtime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLocaltime(java.util.Date localtime) {
        this.localtime = localtime;
    }

}
